language: csharp
solution: Twilio.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.1.5

install:
  - dotnet restore
  - dotnet build --framework netstandard1.4 src/Twilio/Twilio.csproj
  - dotnet build --framework netcoreapp1.1 test/Twilio.Test/Twilio.Test.csproj

script:
  - dotnet run --framework netcoreapp1.1 --project test/Twilio.Test/Twilio.Test.csproj

deploy:
  script:
    - make docker-build
    - make docker-push
  on: tags
