language: csharp
solution: Twilio35.sln
dist: trusty
sudo: required

install:
  - sudo apt-get install -y liblldb-3.6 liblttng-ust0 libunwind8
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-host-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-hostfxr-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-hostfxr-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-sdk-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sdk-ubuntu-x64.latest.deb
  - dotnet --info
  - dotnet restore ./JWT/JWT.csproj
  - dotnet restore ./Twilio/Twilio.csproj
  - nuget restore Twilio35.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - dotnet build /p:Configuration=Release ./JWT/JWT.csproj
  - dotnet build /p:Configuration=Release ./Twilio/Twilio.csproj
  - xbuild /p:Configuration=Release Twilio35.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./Twilio.Tests/bin/Debug/Twilio.Tests.dll
  - nuget pack Twilio.nuspec
