version: '{build}'
image: Visual Studio 2017
configuration: Release
build_script:
- ps: . .\build.ps1
test: off
artifacts:
- path: .\Twilio.*.nupkg
branches:
  only:
    - master
    - alpha
deploy:
  provider: NuGet
  api_key:
    secure: YZzoIwFHwZJOREzsekYHRptdAPDA9/OX1nHmwYRUr0c=
  skip_symbols: false
  artifact: .\Twilio.*.nupkg
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
